# Generated by Django 4.1.2 on 2022-10-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyUser',
            fields=[
                ('u_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user_response_mcq',
        ),
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surveyapi.questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Questions'), ('TEXT', 'Long text')], default='MCQ', max_length=4),
        ),
        migrations.AddField(
            model_name='questions',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveyapi.survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choices',
            name='c_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='s_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_version',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='ur_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user_response_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to='surveyapi.choices'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surveyapi.surveyuser'),
        ),
    ]
