# Generated by Django 3.2.16 on 2023-01-18 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surveyapi.questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveyapi.survey'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='survey',
            field=models.ManyToManyField(to='surveyapi.Survey'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='surveyapi.surveyuser'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='user_response_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to='surveyapi.choices'),
        ),
    ]
