version: '3.8'
services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # mysql:
  #   container_name: MySQL
  #   restart: always
  #   image: mysql:latest
  #   environment:
  #       - MYSQL_ROOT_PASSWORD=surveyapi123
  #       - MYSQL_USER=root
  #       - MYSQL_PASS=surveyapi123
  #       - MYSQL_HOST=127.0.0.1
  #   ports:
  #       - "65015:3306"
  #   expose:
  #       - "65015"
  #   volumes:
  #       - mysql-volume:/var/lib/mysql
  #       - mysql_config:/etc/mysql

  rest-api:
    build: 
      context: ./Rest-API
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Rest-API:/code
      # - mysql_config:/etc/mysql
    ports:
      - "8000:8000"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=surveyapi123
    #   - MYSQL_USER=root
    #   - MYSQL_PASS=surveyapi123
    #   - MYSQL_HOST=127.0.0.1
    #   - MYSQL_PORT=65015
    # depends_on:
    #   - mysql
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  
# volumes:
#     mysql-volume:
#     mysql_config:
