apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.restapi.serviceName }}
spec:
  type: {{ .Values.restapi.service.type }}
  selector:
    app: {{ .Values.restapi.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.restapi.service.port }}
      targetPort: {{ .Values.restapi.service.targetPort }}