apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.frontend.deploymentName }}
  labels:
    app: {{ .Values.frontend.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName }} 
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appName }} 
    spec:
      containers:
      - name: {{ .Values.frontend.appName }}
        image: "{{ .Values.image.repository }}{{ .Values.frontend.appName }}:{{ .Values.frontend.imagetag }}"
        imagePullPolicy: {{ .Values.frontend.pullPolicy }} 
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m