kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: default
  name: {{ .Values.networkPolicyApiAccess.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.restapi.appName }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.frontend.appName }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Values.frontend.appName }}