apiVersion: v1
kind: PersistentVolume
metadata:
  name:  {{ .Values.persistentVolume.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteOnce
  # hostPath:
  #   path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolume.claimName }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}