# Generated by Django 4.1.2 on 2022-10-23 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('c_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('q_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('choices', models.ManyToManyField(related_name='options', to='surveyapi.choices')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('s_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('survey_version', models.IntegerField(default=0)),
                ('questions', models.ManyToManyField(to='surveyapi.questions')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('ur_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user_response_text', models.TextField()),
                ('questions', models.ManyToManyField(to='surveyapi.questions')),
                ('survey', models.ManyToManyField(to='surveyapi.survey')),
                ('user_response_mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to='surveyapi.choices')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('user_response', models.ManyToManyField(to='surveyapi.userresponse')),
            ],
        ),
    ]
