replicaCount: 1

imagePullPolicy: IfNotPresent

namespace: default

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

image:
  repository: docker.io/library/
  tag: latest

frontend:
  appName: frontend
  deploymentName: frontend-deployment
  serviceName: frontend-service
  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
  containerPort: 4200

restapi:
  appName: restapi
  deploymentName: restapi-deployment
  jobName: restapi-job
  serviceName: restapi-service
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  containerPort: 8000

postgres:
  appName: postgres
  deploymentName: postgres-deployment
  serviceName: postgres-service
  configmapName: postgres-config
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  containerName: db
  containerPort: 5432

persistentVolume:
  name: postgres-pv-volume
  claimName: postgres-pv-claim
  storageClassName: manual
  storage: 1Gi

secret:
  postgres:
    name: postgres-secret
  
ingress:
  name: survey-ingress
  config: frontend-config
  hosts: surveyapp.com

ssl:
  certificateName: letsencrypt-ca
  clusterIssuer: letsencrypt-prod
  commonName: surveyapp-32

networkPolicyDb:
  name: db-from-backend
  app: postgres
  fromApp: restapi

networkPolicyNamespace:
  name: deny-from-other-namesapaces

networkPolicyApiAccess:  
  name: api-access

rbac:
  users:
    hugo: sc
    sushmita: sushmita
    jagriti: jagriti

