apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ssl.certificateName }}
  namespace: default
spec:
  isCA: true
  commonName: {{ .Values.ssl.commonName }}
  secretName: {{ .Values.ssl.certificateName }}
  issuerRef:
    name: {{ .Values.ssl.clusterIssuer }}
    kind: ClusterIssuer
    group: cert-manager.io