apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ssl.clusterIssuer }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.ssl.clusterIssuer}}
  namespace: default
spec:
  ca:
    secretName: {{ .Values.ssl.certificateName }}