kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: default
  name: {{ .Values.networkPolicyDb.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.networkPolicyDb.app }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.networkPolicyDb.fromApp }}
          

