kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: default
  name: {{ .Values.networkPolicyNamespace.name }}
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}

