apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
  labels:
    app: {{ .Values.postgres.appName }}
spec:
  selector:
    app: {{ .Values.postgres.appName }}
  type: {{ .Values.postgres.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      nodePort: {{ .Values.postgres.service.nodePort }}