apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  rules:
  - host: {{ .Values.ingress.hosts }}
  - http:
      paths:
      - path: "/"
        pathType: Prefix  
        backend:
          service:
            name: {{ .Values.frontend.serviceName }}
            port:
              number: {{ .Values.frontend.service.port }}
      # - path: /survey
      #   pathType: Prefix  
      #   backend:
      #     service:
      #       name: {{ .Values.restapi.serviceName }}
      #       port:
      #         number: {{ .Values.restapi.service.port }}
      # - path: /admin
      #   pathType: Prefix  
      #   backend:
      #     service:
      #       name: {{ .Values.restapi.serviceName }}
      #       port:
      #         number: {{ .Values.restapi.service.port }}

# ---
# apiVersion: "networking.k8s.io/v1"
# kind: "Ingress"
# metadata:
#   name: "survey-ingress-prod"
#   namespace: "default"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: "/"
#         backend:
#           service:
#             name: "frontend-service"
#             port:
#               number: 80
#         pathType: "ImplementationSpecific"
#     host: "surveyapp.com"
# status:
#   loadBalancer: {}
