kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresdb-pv-volume
  labels:
      type: local
      app: postgresdb
spec:
  storageClassName: minicube-hostpath
  capacity:
      storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
      path: "/opt/postgres/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresdb-pv-claim
  labels:
    app: postgresdb
spec:
  storageClassName: minicube-hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi