apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200