apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 4200
      targetPort: 80