apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  type: ClusterIP
  selector:
    app: restapi
  ports:
    - protocol: TCP
    # Should port be something else here? 
      port: 8000
      targetPort: 8000
      # nodePort: 30000